# Generated by Django 4.0.1 on 2022-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='img',
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
